In [1]:
# Natural Language Processing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Restaurant_Reviews.tsv', delimiter = '\t', quoting = 3)

# Cleaning the texts
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 1000):
    review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, 1].values

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)



[nltk_data] Downloading package stopwords to
[nltk_data]     /home/raushan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
cm

array([[55, 42],
       [12, 91]])

In [4]:
from sklearn.svm import SVC

In [5]:
svc=SVC(kernel='poly',random_state=0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)

/home/raushan/.local/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [6]:
confusion_matrix(y_test,y_pred)

array([[ 97,   0],
       [103,   0]])

In [7]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.485

In [8]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()

In [9]:
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)

In [10]:
confusion_matrix(y_test,y_pred)

array([[74, 23],
       [55, 48]])

In [11]:
accuracy_score(y_pred,y_test)

0.61

In [12]:
from sklearn.linear_model import LogisticRegression
Lg=LogisticRegression(random_state=0)
Lg.fit(X_train,y_train)
y_pred=Lg.predict(X_test)

/home/raushan/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [13]:
confusion_matrix(y_test,y_pred)

array([[76, 21],
       [37, 66]])

In [14]:
accuracy_score(y_pred,y_test)

0.71

In [15]:
from sklearn.tree import DecisionTreeClassifier
Dc= DecisionTreeClassifier(criterion='entropy',random_state=0)

In [16]:
Dc.fit(X_train,y_train)
y_pred=Dc.predict(X_test)

In [56]:
confusion_matrix(y_test,y_pred)

array([[74, 23],
       [35, 68]])

In [57]:
accuracy_score(y_pred,y_test)

0.71

In [17]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [18]:
cm

array([[55, 42],
       [12, 91]])

In [19]:
accuracy_score(y_test,y_pred)

0.73

In [3]:
cv.get_feature_names()

['absolut',
 'absolutley',
 'accid',
 'accommod',
 'accomod',
 'accordingli',
 'account',
 'ach',
 'acknowledg',
 'across',
 'actual',
 'ad',
 'afford',
 'afternoon',
 'ago',
 'ahead',
 'airlin',
 'airport',
 'ala',
 'albondiga',
 'allergi',
 'almond',
 'almost',
 'alon',
 'also',
 'although',
 'alway',
 'amaz',
 'ambianc',
 'ambienc',
 'amount',
 'ampl',
 'andddd',
 'angri',
 'annoy',
 'anoth',
 'anticip',
 'anymor',
 'anyon',
 'anyth',
 'anytim',
 'anyway',
 'apart',
 'apolog',
 'app',
 'appal',
 'appar',
 'appeal',
 'appet',
 'appetit',
 'appl',
 'approv',
 'area',
 'arepa',
 'aria',
 'around',
 'array',
 'arriv',
 'articl',
 'ask',
 'assur',
 'ate',
 'atmospher',
 'atroci',
 'attach',
 'attack',
 'attent',
 'attitud',
 'auju',
 'authent',
 'averag',
 'avocado',
 'avoid',
 'aw',
 'away',
 'awesom',
 'awkward',
 'awkwardli',
 'ayc',
 'az',
 'baba',
 'babi',
 'bachi',
 'back',
 'bacon',
 'bad',
 'bagel',
 'bakeri',
 'baklava',
 'ball',
 'bamboo',
 'banana',
 'bank',
 'bar',
 'bare',
 

In [27]:
m=cv.transform(["I never visited worst place like this place."])
Lg.predict(m)

array([0])